version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "WebOCR"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1aeseqef46lze"
s3_prefix = "WebOCR"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
